LIBRARY	= $(CPPHS)
VERSION	= 1.1

SRCS	= CppIfdef.hs HashDefine.hs MacroPass.hs ParseLib.hs \
	  Position.hs ReadFirst.hs SymTab.hs Tokenise.hs \
	  RunCpphs.hs cpphs.hs

AUX	= README LICENCE* CHANGELOG cpphs.hugs cpphs.compat cpphs.cabal \
		tests/[A-BD-Z]* tests/[a-np-z]* \
		docs/[a-z]* Setup.hs

LIBSRCS	= Language/C/Cpp/CppIfdef.hs \
	  Language/C/Cpp/HashDefine.hs \
	  Language/C/Cpp/MacroPass.hs \
	  Language/C/Cpp/Position.hs \
	  Language/C/Cpp/Tokenise.hs \
	  Language/C/Cpp/RunCpphs.hs \
	  Text/ParserCombinators/HuttonMeijer.hs

all: $(TARGET)
install: $(TARGET)
cfiles: cleanC $(CFILES)
fromC: $(OBJDIR)
	$(LOCAL)/nhc98 -c -d $(OBJDIR) $(CFILES)
	cd $(OBJDIR); $(LOCAL)nhc98 -H8M -o $(TARGET) *.$O
	$(STRIP) $(TARGET)

clean: cleanHi cleanO
cleanO:
	rm -f $(OBJS)
cleanHi:
	rm -f *.hi
cleanC:
	rm -f *.hc *.c
realclean: clean cleanC
	rm -f *.raw *.html haddock.css haskell_icon.gif
	rm -f $(TARGET)
package:
	tar cf tmp.tar $(SRCS) $(AUX)
	mkdir cpphs-$(VERSION)
	cd cpphs-$(VERSION); tar xf ../tmp.tar
	tar zcf cpphs-$(VERSION).tar.gz cpphs-$(VERSION)
	zip -r cpphs-$(VERSION).zip cpphs-$(VERSION)
	rm -r tmp.tar cpphs-$(VERSION)
haddock: $(SRCS)
	haddock -h $(SRCS)


$(CPPHS): $(OBJDIR) $(OBJS)
	$(HC) $(HFLAGS) $(HEAP) -o $@  $(OBJS)
	$(STRIP) $@

$(OBJDIR):
	mkdir -p $(OBJDIR) || $(TRUE)
$(OBJS): $(OBJDIR)/%.$O : %.hs
	$(HC) $(HFLAGS) -c -o $@ $<

$(CFILES): %.$C : %.hs
	$(HC) $(HFLAGS) -C $<


# dependencies generated by hmake -Md:
${OBJDIR}/MacroPass.o:	${OBJDIR}/HashDefine.o ${OBJDIR}/Tokenise.o \
			${OBJDIR}/SymTab.o 
${OBJDIR}/HashDefine.o:
${OBJDIR}/Tokenise.o:	${OBJDIR}/HashDefine.o 
${OBJDIR}/ReadFirst.o:	${OBJDIR}/Position.o ${OBJDIR}/SymTab.o 
${OBJDIR}/Position.o:
${OBJDIR}/ParseLib.o:
${OBJDIR}/SymTab.o:
${OBJDIR}/CppIfdef.o:	${OBJDIR}/SymTab.o ${OBJDIR}/ParseLib.o \
			${OBJDIR}/Position.o ${OBJDIR}/ReadFirst.o \
			${OBJDIR}/Tokenise.o 
${OBJDIR}/RunCpphs.o:	${OBJDIR}/CppIfdef.o ${OBJDIR}/Position.o \
			${OBJDIR}/MacroPass.o 
${OBJDIR}/cpphs.o:	${OBJDIR}/RunCpphs.o 

# C-files dependencies.		-- (needs updating)
MacroPass.hc:	HashDefine.hc Tokenise.hc SymTab.hc 
HashDefine.hc:
Tokenise.hc:	HashDefine.hc 
ReadFirst.hc:	Position.hc SymTab.hc 
Position.hc:
ParseLib.hc:
SymTab.hc:
CppIfdef.hc:	SymTab.hc ParseLib.hc Position.hc ReadFirst.hc Tokenise.hc 
RunCpphs.hc:	CppIfdef.hc Position.hc MacroPass.hc 
cpphs.hc:	RunCpphs.hc
